name: Debug Test

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: List all files
      run: |
        echo "=== Repository structure ==="
        ls -la
        echo "=== Data directory ==="
        ls -la data/
        ls -la data/job_descriptions/
        echo "=== Scripts directory ==="
        ls -la scripts/
        echo "=== Templates directory ==="
        ls -la templates/
    
    - name: Test Python
      run: |
        python3 --version
        python3 scripts/test_simple.py test arguments
    
    - name: Check LaTeX
      run: |
        which pdflatex || echo "pdflatex not found"