name: Generate Tailored Resume

on:
  workflow_dispatch:
    inputs:
      job_file:
        description: 'Job description JSON file name'
        required: true
        default: 'example_job.json'
      output_name:
        description: 'Output name (without .pdf)'
        required: true
        default: 'tailored_resume'

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra
    
    - name: Generate Resume
      run: |
        python scripts/generate_resume.py data/job_descriptions/${{ github.event.inputs.job_file }} ${{ github.event.inputs.output_name }}
    
    - name: Upload Resume
      uses: actions/upload-artifact@v3
      with:
        name: resume-${{ github.event.inputs.output_name }}
        path: output/${{ github.event.inputs.output_name }}.pdf